### ISSUE TITLE
Vote for a track

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#110]
As for now a user can suggest a song.
From here we need to allow a user to vote for a song.
Note: a user can vote for several tracks in a row, we do not need to wait the end of the operation
Then add a score to each track, depending on this score order the tracks list from the highest score to the lowest.
The first one, the track with the highest score, will be the next played ( or the first played ).
During the room creation the creator can defined the minimum score needed for a track to be played.
For the moment, until the room creation pull request/dev, this data will be mocked to 2 votes.
In this way a track will be found under two statuses:
1- About to be played, eligible score >= minimum score
2- Suggested tracks, score < minimum score
No matter the track status any tracks can receive votes until he's loaded in the player
When a user has voted for a track he cannot remove his vote.
A user can vote for a track by clicking on the track card, from the track's list in the music player full screen view.

When a user has voted for a song a visual element needs to notify the operation ( e.g change track card background color ).
Note: This involve to persist the user vote between every user devices => to develop

After a user has voted for a song every other room's members need to see their track's list score & order updated.
The suggestedTracks & eligibleTracks arrays order are deterministic 

**_New sockets event:_**
**From Client:**
1.  Vote for a track -> `USER_VOTE_FOR_TRACK`

**From server:**
User related:
1. Vote for a track temporal response -> `USER_VOTE_FOR_TRACK_CALLBACK`
The above socket event includes the user's voted for tracks , inside the `state.userRelatedInformations.`

Global scope:
1. Score has been updated for a track in the list -> `TRACK_LIST_SCORE_UPDATE`
This could really be heavy to send a socket event for every user's vote. Maybe shall we want to perform a
TRACK_LIST_RECURRENT_SCORE_UPDATE. that would be triggered every T seconds by temporal

Client:
- [ ] #122
- [x] #121
- [x] Print track score confronted to the minimumScoreToBePlayed in the tracks card list
- [x]  Modify the suggest user related callback to persist a state copy to merge in the state machine, to notify the state machine that user has voted for the suggested track
- [x] Emit a `USER_VOTE_FOR_TRACK` by pressing on a track card.
- [x] Notify to the user tracks he has already voted for. By pressing on these nothing will occurs.
- [x] In the AppMusicPlayer listen to the `USER_VOTE_FOR_TRACK_CALLBACK` and merge the given state.
- [x] In the AppMusicPlayer listen to the `TRACK_LIST_SCORE_UPDATE` and merge the given state.
- [x] Tests

Server:
- [x] In socket.ts create a listener/handler for `USER_VOTE_FOR_TRACK` and persist the operation to temporal
- [x] Create a route and handler for the temporal response to `VOTE_FOR_TRACK` operation. From there emit a `USER_VOTE_FOR_TRACK_CALLBACK`
- [x] ~~Create a route and handler for the temporal `trackListScoreUpdate` activity. From there emit a `TRACK_LIST_SCORE_UPDATE` to every user in room~~ Handled in the SuggestOrVoteActivity thread
- [x] Tests

Temporal
- [x] Add to the internalStateUser definition an array for user voted track.
- [x] Remove SuggestedTrack array from the internalState, only use Tracks array and differentiate suggested to toBePlayed tracks based on their score, also update tests
- [x] Create a route and a handler for the `userVoteForTrack`
- [x] Handle the `userVoteForTrack` signal in the workflow
- [x] Populate user `votedForTracks` array after `userVoteForTrack` signal then send back two activity one user related `userVoteForTrackCallback` and an other one not user related `trackListUpdate` both given state as parameters.
- [x] After a suggest if the suggested track is already in the mtv room tracks list just increment the track score by one. Still sending back suggest user related activities to fulfill client expectations.
- [x] Initial tracks are counted as creator voted by
- [x] After a suggest the injected suggestedTrack will get score = 1 and user tracksVotedFor will be append from the suggested track. Just to say that a user suggesting a track is also automatically voting for it
- [x] Create a method to sort the tracks list arrays directly in temporal after a score's update, in the vote for track signal management
- [x] When a track is loaded in the player as a current track it must be removed from every TracksVotedFor users's array. The only way we have, without giving our souls the evil, is to loop over every users searching for the track ID that has been loaded.
We've discuss about the idea of storing the source  of truth, and even about iterating with two sources, somewhere else from the user definition.
We conclude this would be the optimal performances place, better than the track itself
- [x] refactor the deepEqual tracks methods using a custom function and not reflrect.DeepEqual
- [x] Cannot suggest the currentTrack
- [x] To notify to every users in the room use as for a suggest than a vote the activity/route
- [x] To do not overload the temporal service send the described above activity using an interval that will be init after a vote or a suggest into vote and die if the interval get the same state between two timeout
- [x] If a track has a score less than the minimumScoreToBePlayed he can't be assign as the next current track. In this way in the method assign next track do not allow a low score track to be loaded.
- [x] With the very initials tracks, if the minimumScoreToBePlayed is higher than 1, does the first one will not be auto played/loaded in the player he will need to become playable such as every other tracks.
- [x] Handle the minimumscore init in the create route
- [x] Make fail the go to next track that achieves to the music player freeze
- [x] When no more track are playable in the list, go to pause state and listen to the tracks score update to auto play if possible the very next playable track
- [x] Tests

**Comment by Devessier** [comment]
**?? No matter the track status any tracks can receive votes until he's loaded in the player ??**

> A: I think it is necessary so that tracks can continue to gain places in the tracks list.

**Comment by Devessier** [comment]
**??Note: This could really be heavy to send a socket event for every user's vote. Maybe shall we want to perform a
TRACK_LIST_RECURRENT_SCORE_UPDATE. that would be triggered every T seconds by temporal ??**

> I think you are right, this would be too much. Now we have to find a correct number of seconds.

**Comment by Devessier** [comment]
**After a suggest if the suggested track is already in the mtv room tracks list just increment the track score by one. Still sending back suggest user related activities to fulfill client expectations ( ?? but maybe not for the global activity ??).**

> A: To keep things simple, I think that we should not introduce differences and treat every vote the same.

**Comment by Devessier** [comment]
**After a suggest the injected suggestedTrack will get score = 1. Just to say that a user suggesting a track is also automatically voting for it**

> A: Agree.

**Comment by prastoin** [comment]
> **After a suggest if the suggested track is already in the mtv room tracks list just increment the track score by one. Still sending back suggest user related activities to fulfill client expectations ( ?? but maybe not for the global activity ??).**
> 
> > A: To keep things simple, I think that we should not introduce differences and treat every vote the same.

We cannot as we need to bring more informations into the userRelatedInformations such as the tracks the user has voted for since now

**Comment by prastoin** [comment]
> **Create a method to sort the tracks list arrays directly in temporal**
> 
> > A: I think it's a great idea to sort the list server side and let the client only display it. The question now is whether we want to keep a sorted list up to date or if we want to sort it when exporting the state.

I think we should sort it only on score's update, as export theoretically will be called much more than just the vote signal thread

**Comment by Devessier** [comment]
I think we should keep in mind what we decided during the Shaping process.

_What if two songs in the queue have the same votes count ?_
**The first one that has reached this count will be played first.**

**Comment by Devessier** [comment]
I agree. It's not a bad idea to use initial index in the slice.
And it's quite easy in Go: https://pkg.go.dev/sort#Stable.

-----

Sorry, I did not read carefully enough.

**Comment by prastoin** [comment]
Remark:
A tracks cannot have a score = 0.

**Comment by prastoin** [comment]
I was wondering the necessity of havin a miniScoreToBePlayed :thinking: 
Then I remembered we needed it to play only voted song for public room where only invited users can vote
We should also keep in mind this

`
If a track has no counts it won't be played, the minimum count needed for a song to be played is defined by the room's creator, and the minimum value is 1 knowing that if a user suggests a song he automatically votes for it, if he has the permissions to do so. Orelse it will just add the song to the pool with 0 vote.
If a user with voting permissions suggests a song already present in the queue it will vote for it.
`
Also there's one more thing to be done in this PR is to disallow a track with a score < minimum score to be loaded in the player
If there's no track to play, no music will be played during what ever time it takes to one to become playable

**Comment by prastoin** [comment]
I've written an article concerning the auto play described in this issue
https://3.basecamp.com/4704981/buckets/22220886/messages/4122481540
