### ISSUE TITLE
Delegation & mode management

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#135]
This PR will treat the delegation feature and the moode implementation.
The mode and delegation are very bound. As the difference between the two modes, direct and broadcast is defined by the delegation feature.
Inside a direct mode appears a new permissions and new mecanism, the delegation.
At the moment, as for a broadcast room, every user is an emitter, which means has one device playing the music.
Inside a direct mode it's not the same, only one user can be emitter at the time.
The delegation is the ability to determine who is the only emitter in an direct mode room.

Delegation involves few rules and principles: 
- To be in a direct mode room
- A new permission, the permission to choose who will own the delegation
- Permission given by default to invited friend included in the control & delegation permission, or a permission included in the control & delegation permission the creator can toggle to what ever user
- A new operation, the operation to give/make a user the delegation owner, operation that could be execute only by users having the above described permission.
- Someone that we could call the delegation owner that could not or do have the delegation permission

Client:
- [x] handle `UPDATE_DELEGATION_OWNER` workflow inside the music player state machine
- [x] listen to `UPDATE_DELEGATION_OWNER_CALLBACK` an merge the given state
- [x] In a direct room if the user is not the delegation owner mute his music player ( shall we also hide the change emitting device cta ? )

Server:
- [x] Create and handle new client socket event `UPDATE_DELEGATION_OWNER`. persist to temporal
- [x] create and handle `UPDATE_DELEGATION_OWNER` temporal callback activity and persist to front via a `UPDATE_DELEGATION_OWNER_CALLBACK` to every room users

Temporal:
- [x] Create a new props in the internal state called delegationOwnerUserID uuid or null. This props will be used to notify to every room user's who is the delegation owner. Also it will allow to mute the music player of the nun delegation owner. We will not store this information in the userRelatedInformation as it's a global information. A userID is not a security leak as could be a deviceID
The props will be set as null for broadcast room, also the default value will be the creator userID
- [x] Add a controlAndDelegationPermission bool, default false even for broadcast room. Invited user and creator will have the bool to true.
- [x] Create a route and signal to allow the delegation owner udpate. This operation will be executable only by user having the control & delegation permission.
- [x] Create an  sendUpdateDelegationOwnerCallback activity to notify every user about the new delegationOwner
- [x] On delegation owner leave room operation set the creator as default delegation owner again
- [x] tests

**Comment by Devessier** [comment]
Some part of the job has been isolated into [another issue](https://github.com/AdonisEnProvence/MusicRoom/issues/139).
