### ISSUE TITLE
User search engine

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#164]
You can find the user search engine definition [here](https://3.basecamp.com/4704981/buckets/22220886/messages/3751924163#:~:text=operations%20see%20above.-,User%20Search%20Engine,-Regroups%20a%20search)

Client:
 - [x] Create a new modal as screen for the user search engine.
 - [x] Inside this view, as for the mtv room search engine, will be found a seach bar in the header. The users will be searched by their nickname only using lucid pagination. Again such as for the mtv room search engine.
- [x] By default the user search engine will list the user's friend inside a flat list. The friend list will also use the pagination.
- [x] Users will be listed using the existing UserListItem.tsx, already used inside the mtv room users list, but this time without any actions.
 - [x] Tests
 
Server:
- [x] Handle a user search engine pagination

Types:

**Comment by Devessier** [comment]
We should probably create a table `users_friends` and let users have many users as friends, that is, creating a `many to many` relation between `users` and `users`.

**Comment by prastoin** [comment]
Yes you're right
I think we should be implementing the friends funnel after the invitation one.
It will be time later to come back on this issue or maybe to isolated this issue friends related tasks into a new one
