### ISSUE TITLE
User should be able to know if a given room has specific constraint for voting

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#187]
The user should be able to know if he's about to join a room with either :
- time and position constraint
- onlyInvitedUserCanVote constraint

From a music room a user should be able to determine if he fits the room constraint he's joined
- [ ] Add an icon ??somewhere?? to notify the user that the time constraint is expired ( nothing if it's ok, as it's not depending on the user actions we want him to know only when it's false )
- [ ] Add an icon ??somewhere?? to notify the user that he need to be invited if the room is in onlyInvitedUsersCanVote.
- [ ] Add an icon ??somewhere?? to notify the user that he fits the position constraint and or doesn't fit the position constraint
- [ ] We should allow the user to know where the position constraint radius is located, in this way we should be saving coords and a radius somewhere and we might need to print a map somewhere in the front

To summary when disabling a track card in the list we should be declaring to the user why.
Then we might want to show to the user the icon in the tracks tab

**Comment by prastoin** [comment]
https://docs.expo.dev/versions/latest/sdk/map-view/

Test using beta version on web

**Comment by prastoin** [comment]
We want every user in room with constraint to be able to know what are the constraint, where for the position and when for the time constraint. But we also want the user to be able to know he fits the given constraint.
In this way in the music player fullscreen we should add a button, might be in the page header next to the dismiss fullscreen player chevron, whom will redirect the user to a specific screen

When entering the screen we will ask for the device position if it's not already done.
The screen will display an expo map with the given position radius and center. We could also display the user current location.
A button will be visible to the user if we don't have access to his device position, this button will trigger the device location request and location watcher.
The user will see on the map the room position constraint, center and radius, and his current device position. ??The default map zoom should allow to see both at the same time ?? => why not if this isnt a pain and that it renders well.
The user will only be able to zoom and unzoom in the map, nothing else.
The map will be as minimalist as possible.
As far as time constraint is concerned a simple start and end date will be enough.

The redirect button in the music player won't be the same for a client that fits every constraint and one that doesn't fit at least one constraint

**Comment by Devessier** [comment]
It seems great to me.
Do we show something special on the map if another device of the user meets physical constraints?

**Comment by prastoin** [comment]
> Do we show something special on the map if another device of the user meets physical constraints?
I think you're right, displaying a map with a dot outside of the given radius and saying: you're fitting the position constraint can be quite disturbing.
But i'm not sure this development is 100% worth it, this involves creating a specific socket event to retrieve a new dto type computing new data.. We do not store anywhere, neither adonis or temporal, a specific value concerning a given device and the position constraint. Our policy tends to an all in one status, does the user fits the position constraint with at least one of his device ?

Maybe the simpliest solution is to only display the current device position if the user doesnot fits the position constraint ?
And below the map if the position constraint is respected tells `at least one of your device is in the given radius`

Maybe I'm wrong and we need to go deeper and create new specific tools as described before

**Comment by Devessier** [comment]
I think you're original proposition is quite good!
We always show the map with the position of the device, and we display a text (as you said, `at least one of your device is in the given radius`) that tells if the user fits physical constraints. 👌 
I wanted to be sure that we don't want to overcomplicate this feature.

**Comment by prastoin** [comment]
Great about to write down a todo list soon

**Comment by prastoin** [comment]
Client:
- [ ] Create a new modal screen called `MtvRoomConstraintPreview` that will take in params the roomName the room position cosntraint mainly lat lng + radius. Time constraint startsAt and endsAt
- [ ] By entering the screen it should request the foregrroundLocationPermission
- [ ] The `MtvRoomConstraintPreview` should display a expo map with a cricle centered on the room position constraint lat lng and radius
- [ ] In the map should always appears the current device position if we have it
- [ ] The map should have a default zoom that allows the user to see both it's device position and the room position constraint zone
- [ ] If it's easy to be done, the user should only be able to zoom in and out.
- [ ] If the user fits the position constraint a label saying `You fit the room position constraint, at least one of your device is in the zone`
- [ ] Concerning the time constraint In the screen the user should be able to find a simple Text following the pattern 'Starts: yyyy mm/dd 00:00 Ends: yyyy/mm/dd 00:00'

**Comment by prastoin** [comment]
TODO
- [ ] Refactor map container
- [ ] Add infos about time constraint
- [ ] Ask for device location permission when entering the screen
- [ ] Add label You fit the room position constraint, at least one of your device is in the zone
- [ ] ?? Add a label about time constraint status ??
- [ ] Add a button to allow the user to give it's device location permission, ??just display the button all the time??

**Comment by prastoin** [comment]
Rename Maps folder to RoomConstraintsMap

**Comment by prastoin** [comment]
Use React.reactNode instead of reat.Element for nullable jsx element
