### ISSUE TITLE
Fix the goBack after entering the mtvRoomCreation form 

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#189]
The go back after joining the mtvRoomCreationForm displays a white page

**Comment by Devessier** [comment]
In appMusicPlayerMachine, we would expect the context to be reset after the modal has been closed.
But in XState 4, assign actions are always called before any other action.
Therefore the context is reset before we could pick from it the function to close the modal and call it.

![CleanShot 2021-11-17 at 12 25 50@2x](https://user-images.githubusercontent.com/29370468/142193480-628b859c-f290-4c5c-94bd-a377e8d19c6f.png)

**Comment by Devessier** [comment]
This issue can be easily solved by using `preserveActionOrder` option on the state machine.
See https://github.com/statelyai/xstate/blob/main/packages/core/CHANGELOG.md#minor-changes-3.
