### ISSUE TITLE
Socket events receiving during socket registration

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#197]
We discovered that sometimes messages are send by the frontend to the backend while the backend is still [registering the device](https://github.com/AdonisEnProvence/MusicRoom/blob/master/packages/server/start/socket.ts#L31-L37).

Let's discuss about possible solutions here.

Bug explained here: https://cln.sh/QahBcZ [French].

**Comment by prastoin** [comment]
We should be listening to this event before the device registration then we should be implementing a retry policy
Either:
-Back only with why not a try catch scoped to the socketGetCredentials step with a retry interval with maximum retry that achieve to a re throw
-Front side and back side, on back fail emit a specific event that achieves to a retry from the client itself

**Comment by Devessier** [comment]
The issue is that the frontend sends events before the backend is ready.
One solution would be to delay sending messages until the backend is ready.

We could send a message from the server to the client when the device has been registered/fetched like that:
<img width="1086" alt="CleanShot 2021-11-10 at 18 49 32@2x" src="https://user-images.githubusercontent.com/29370468/141166206-4785a838-c83d-4d6c-bcde-1653b6dec76a.png">

Then we would have to listen this event in frontend and allow actions only when the backend confirmed to be ready.

**Comment by prastoin** [comment]
I agree with your proposition
We should then update the userMachine to allow actions only after the client receives his deviceID

**Comment by Devessier** [comment]
Has already been closed by a PR: https://github.com/AdonisEnProvence/MusicRoom/pull/202.
