### ISSUE TITLE
Simplify SearchTracks screens

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#257]
Currently there is one screen to hold an input to search for tracks, and another screen to hold results.
We implemented this feature that way because at the beginning of the project we wanted to show special information on SearchTrackScreen, such as the history of searches.
I don't think we will ever implement that, and the current implementation is not great.
We had to find a hack to reset the search bar on SearchTrackScreen after a room has been created (see #247). As a consequence, we can not go back to the search bar if the results are not satisfying because it is reset when we enter back on the screen!

Everything would be so much easier if we were using patterns we developed more recently, such as on `MusicTrackVoteSearchScreen`: a single screen that holds search bar and results. No more headache to reset the input whenever we want.

**Comment by prastoin** [comment]
I Agree !
