### ISSUE TITLE
Fix hardware previous button on the trackPlayer

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#28]
After loading a track in the player and clicking on it to go the the MusicTrackPlayerScreen by hitting the previous hardware button react navigationd do not redirect to the previous page. Because we're emulating a kind of redirection that is a real one

**Comment by Devessier** [comment]
On Spotify for Android when the hardware back button is pressed and the player is opened in fullscreen, the player is dismisssed.

**Comment by Devessier** [comment]
Before fixing this issue we should see if it can be avoided.
