### ISSUE TITLE
MPE Tracks List Editing - Adding a track

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#283]
## Temporal

- [x] Receive a signal with tracks IDs to add (`AddTracks`)
- [x] Keep only tracks not currently in the playlist before fetching their information
- [x] Fetch tracks information
- [x] Keep only tracks not currently in the playlist after fetching their information
- [x] If no tracks could be added (because of duplicates) send an error to the device that tried the operation (request `/mpe/reject-adding-tracks`)
- [x] If tracks could be added, forward updated tracks list to all users and acknowledge the operation (request `/mpe/acknowledge-adding-tracks`)
- [x] Create route `/mpe/add-tracks` that sends `AddTracks` signal to the workflow

## Server

- [x] Wait for `MPE_ADD_TRACKS` WS event and request `/mpe/add-tracks` route of Temporal
- [x] Create route `/mpe/reject-adding-tracks`
- [x] Send `MPE_ADD_TRACKS_FAIL_CALLBACK` WS event to the device that tried the operation
- [x] Create route `/mpe/acknowledge-adding-tracks`
- [x] Send `MPE_TRACKS_LIST_UPDATE` WS event to all devices
- [x] Send `MPE_ADD_TRACKS_SUCCESS_CALLBACK` to the device that added the track

## Client

- [x] Create a screen to pick a track to add to the playlist (`MusicPlaylistEditorSearchTrackScreen`)
- [x] When a track is picked, send a `MPE_ADD_TRACKS` event to the server
- [x] When receiving `MPE_ADD_TRACKS_FAIL_CALLBACK`, show an error toast
- [x] When receiving `MPE_ADD_TRACKS_SUCCESS_CALLBACK`, show a success toast and update tracks list
- [x] When receiving `MPE_TRACKS_LIST_UPDATE`, update tracks list

## Notes

~~We only check for duplicates after tracks to add information have been fetched because tracks can be deleted in the meantime.~~
~~_Is this really the expected behaviour?_~~

A: We remove duplicates before and after information fetching.

**Comment by prastoin** [comment]
> We only check for duplicates after tracks to add information have been fetched because tracks can be deleted in the meantime.
> _Is this really the expected behaviour?_
 I think we should be doing the same as we do in the MTV.
 We check for duplicated track before fetching more information, but also after given track fetched information is finished as there is a race condition risk

**Comment by prastoin** [comment]
I think we should also mimic the mtv SUGGEST_TRACK mechanic by sending back two specific server socket event:
MPE_ADD_TRACK_CALLBACK -> toward add track emitting user device -> displays a success toast on the given device only
MPE_TRACKS_LIST_UPDATE -> toward every users in the room

It involves to persist through temporal the operation emitting device ID
