### ISSUE TITLE
Potential seldom race condition between trinity MPE creation

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#292]
There's a very tiny race condition risk, where the client receives the CREATE_MPE_ROOM_CALLBACK before the CREATE_MPE_SYNCED_CALLBACK
The actor wouldn't be already spawned in the machine

**Comment by Devessier** [comment]
There is almost no chance that it occurs in real world.
It can occur only in a simulated environment, such as in tests.
