### ISSUE TITLE
Verify that youtube player screen is not deleted while performing operation in a mpe view

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#320]
We should have declared navigator that do not delete previous screen
Should double check this point

**Comment by Devessier** [comment]
We will create a E2E test that checks that multiple operations on MTV player and on MPE rooms don't break anything.

**Comment by Devessier** [comment]
See https://github.com/AdonisEnProvence/MusicRoom/issues/384.
