### ISSUE TITLE
MPE Search Engine - Plan

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#330]
To be fully implemented, we need invitations for MPE rooms to have been developed.

## Behaviours

Users find all public rooms, and rooms they were invited in.
The order is: private rooms > public rooms with invitation > public rooms.
**We don't display rooms the user has already joined.**

As for MTV Search Engine, we show all rooms when there is no search query, and then filter by the search query.

When a user presses a MPE room card, we redirect her to the screen displaying room information.

## Todo

- [x] #331
- [x] #332

**Comment by prastoin** [comment]
All tasks have been done, closing plan issue
