### ISSUE TITLE
MPE Search Engine - Client

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#331]
## Todo

- [x] Implement Infinite Scroll
- [x] Create integration tests with @xstate/test

### Playlist Actors spawning

When we press a playlist, we spawn a Playlist actor before redirecting the user to the room screen. If an actor for this room already exists, we only redirect the user to the room screen.

The actor directly loads room context. After that, and if the user has joined the room, the actor listens to updates sent by the server, but it never reloads room context by itself.

We keep the actor alive after we exit the room screen.

We apply these principles to all screens where we can press on a MPE room card.

[See statechart](https://stately.ai/viz/embed/c44fc4bb-45fe-4caf-af90-4643988ea03a?mode=viz&panel=code&showOriginalLink=1&readOnly=1&pan=1&zoom=1&controls=1)

**Comment by prastoin** [comment]
> The actor directly loads room context. After that, the actor listens to updates, but it never reloads room context.

If the user has not already joined the clicked room, right ?

**Comment by Devessier** [comment]
I modified the description accordingly.

**Comment by fabform** [comment]
Handy alternative list of [alternative search engines](https://fabform.io/a/alternative-search-engines)
