### ISSUE TITLE
Join MPE room client

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#334]
# Client implementation of the JOIN MPE ROOM feature

We should keep in mind that user is joining room from the moment he's hit the JOIN button in the mpe room Preview
This is not the goal of this issue, here we want to implem everything under the JOIN button hood onyly, lets have headache later on the UI.

- [x] Hack a join mpe room button in the homeScreen lets be creative
- [x] In the `AppMusicPlaylistsMachine` we should listen in `SocketConnection` service to the new server socket event:
 - `MPE_USERS_LENGTH_UPDATE` and forward it to the related mpe actor, will achieve to a basic `assignMergeNewState` event
 - `MPE_JOIN_ROOM_CALLBACK` that will be fowarded to the related playlist actor
- [x] We should create a method that takes an operation and check if actor is existing if not proceed to spawn it and then perform the given operation toward the just spawned actor

## To be determined
- [x] Create a new Event pair between an `playlistMachine` and it's parent `AppMusicPlaylistsMachine` for the `MPE_JOIN_ROOM` workflow. Event will be forwarded to the parent then to the `SocketConnection` service achieving to sending a `MPE_JOIN_ROOM` client socket event to the server
Why from the playlist itself ? because as said in the beginning of the issue the action of joining room will be triggered inside the room preview **Choosen one**

>OR

>- [ ] Create a basic listener in the `AppMusicPlaylistsMachine` for the `MPE_JOIN_ROOM` event that will take a `roomID`, the event will be forwarded to the `SocketConnection` service achieving to sending a `MPE_JOIN_ROOM` client socket event to the server

**Comment by Devessier** [comment]
As we discussed in https://github.com/AdonisEnProvence/MusicRoom/issues/345, playlists actors will be spawned before we enter in the room, so that there is always an alive actor for a displayed room.
Therefore `MPE_JOIN_ROOM_CALLBACK` WS event should be forwarded to the actor of the concerned playlist.
