### ISSUE TITLE
Leave MPE room client

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#338]
# Client implementation of the LEAVE MPE ROOM feature

We should keep in mind that the leave button will be accessible from a bottom sheet modal via a settings button in the mpe room view.
From now we just want a static button in the mpe room view that will lead to perform a `MPE_LEAVE_ROOM` of the currently viewing mpe room

- [x] Hack a leave mpe room button in the related mpe room view
- [x] Add a server socket event listerner into the `AppMusicPlaylistsMachine` `socketConnection` service for the `MPE_LEAVE_ROOM_CALLBACK` that will lead to stop the related mpe Actor from the event payload `roomID` and will redirect the user view to it's library tab
- [x] Create a new Event pair between an `playlistMachine` and it's parent `AppMusicPlaylistsMachine` for the `MPE_JOIN_ROOM` workflow. Event will be forwarded to the parent then to the `SocketConnection` service achieving to sending a `MPE_JOIN_ROOM` client socket event to the server
- [x] Add a server socket event listerner into the `AppMusicPlaylistsMachine` `socketConnection` service for the `MPE_FORCED_DISCONNECTION` that will lead to stop the related mpe Actor from the event payload `roomID` and redirect to home
- [x] After a forced disconnection or a leave callback only client currently displaying the related mpe room view should be redirected
- [x] tests
- [x] e2e test b and c

**Comment by Devessier** [comment]
When we receive a `MPE_LEAVE_ROOM_CALLBACK` WS event, what do we do? Do we go back to MPE Rooms List screen?

**Comment by prastoin** [comment]
> When we receive a `MPE_LEAVE_ROOM_CALLBACK` WS event, what do we do? Do we go back to MPE Rooms List screen?

I guess we should display the previous screen ?

**Comment by Devessier** [comment]
Or we could rely on a more deterministic behaviour and redirect the user to MPE Rooms List screen, as we don't necessarily know on which screen the user was.
This redirection is part of the user experience we want to provide. When a user leaves a MPE room, where does she want to be redirected?
