### ISSUE TITLE
MPE Library Search Engine - Plan

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#341]
## Behaviours

Users can scroll down to see all the rooms they joined.
There is infinite loading. There is a search bar to filter results, that uses infinite loading too.

When users press MPE rooms cards, they are redirected to the screen of the room.

## Implementation

See https://github.com/AdonisEnProvence/MusicRoom/issues/331 about Playlist actors spawning.

## Todo

- [x] #342
- [x] #343
- [x] https://github.com/AdonisEnProvence/MusicRoom/issues/387
- [x] https://github.com/AdonisEnProvence/MusicRoom/issues/388

**Comment by prastoin** [comment]
All tasks have been done, closing plan issue
