### ISSUE TITLE
Implement E2E test for MPE Library Search Engine

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#388]
We need to find a way to test this screen.
We need to check how we tested MTV Search Engine.

**Comment by prastoin** [comment]
As far as mtv room search engine is concerned we were testing it indirectly through the mtv core feature e2e coverage
It's atm the same for the mpe, we're using the lib search engine but also the global mpe rooms search engine through each tests depending on if the user is the tested mpe room creator or just a member
Closing
