### ISSUE TITLE
Expand music player after creating or joining mtv room

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#392]
after receiving a MTV_ROOM_SYNCED_CALLBACK or a MTV_ROOM_CREATE_CALLBACK, we should toggle on the music player fullscreen

this should also fix the following issue: https://github.com/AdonisEnProvence/MusicRoom/issues/375

**Comment by prastoin** [comment]
Do we also want to expand the music player after joining a room ?

**Comment by prastoin** [comment]
Client:
- [ ] Update AppMusicPlayerStateMachine to redirect view after create and join
- [ ] Udpate client integ tests
- [ ] Update e2e tests

**Comment by Devessier** [comment]
This issue does not close https://github.com/AdonisEnProvence/MusicRoom/issues/375.
