### ISSUE TITLE
Backend spotify Auth

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#5]
Create an api that allows the user to login with his spotify account, and then add our application to his whitelist.
No need for the moment to persist the token if it's not in node instance. We just want, during the first devs, to have a smooth communication with the spotify api

**Comment by Devessier** [comment]
In Spotify documentation we can find several authentication methods that can serve our goals.
The [Authorization Code Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow) is probably the easiest way to keep a user authenticated.
There is another method that needs to be clarified: [Authorization Code Flow with Proof Key for Code Exchange](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce).

Before choosing a method or another we need to go deeper in the understanding of both methods.

**Comment by Devessier** [comment]
As described in [SDK management issue](https://github.com/AdonisEnProvence/MusicRoom/issues/7) issue, we will use YouTube instead of Spotify.
Spotify Authentication is no longer a requirement.
