### ISSUE TITLE
e2e email verification retrieve token

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#525]
See https://github.com/AdonisEnProvence/MusicRoom/issues/486 comments to understand this issue's redaction

We need to be able to retrieve a dynamic token in the e2e tests
There could be two ways to do so:

## Alive inbox
We could open a temp email page retrieve the generated email and sign up using it, then on sign up the server will send a email confirmation mail to the given email ( that is alive in a of the browser tab ).
We would scrap the open page and retrieve the token from the received email
This would be quite wobbly because we would be dependent on on an external website such as [temp-mail](https://temp-mail.org/fr/) or [mail7](https://mail7.io/)
This could still be a good solution associated with the second solution the `e2e test private route`

## e2e test private route
We could set up a route inside the server api that would return the last created email verification token for a given email.
This route should be guarded, this would allow to retrieve related authenticated user email confirmation token easily.
This route should only be available in e2e tests, see .env variables ?
This route would be called via playwright requester, which means inside e2e test context only

### EDIT
We've completly forgotten about the fact that we will be storing hashed token in databse, in this way it's impossible to retrieve it after it's creation.
To face this issue, we will still implement an authenticated e2e test specific route that will change the authenticated user isEmailConfirmed value directly in database without awaiting for any token

## Conclusion
In my opinion better the coverage will be if we achieve to be using both of the solutions !
Only one e2e test, that could be a specific sign-up e2e test would be using the described `Alive inbox` and every other one would be using the `e2e test private route` via centralized testUtils methods

### Sending email in e2e tests inside testUtils performSignup
We've discovered that while running any e2e test, as they all perform a sign up an email will be sent to a random generated email. This is not cool.
To face this issue, we need to create a route to be able to toggle Mail.trap() ( it this works ).
The route would be called something like `/test/toggle-mail-trap`

**Comment by Devessier** [comment]
I agree with you! We can use both solutions.

**Comment by prastoin** [comment]
Closing issues as it has been resolved
