### ISSUE TITLE
Generate Swagger documentation of the API

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#569]
We can make use of https://github.com/ad-on-is/adonis-autoswagger to automatically generate the Swagger documentation of the API.

**Comment by Devessier** [comment]
Maybe should we find a way to improve the documentation automatically generated, but I don't even if we want to allocate a lot of time for this task.

**Comment by prastoin** [comment]
Each routes should have a small description toward the business logic
Temporal ack routes will be ignored
