### ISSUE TITLE
Application global layout modifications

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#571]
To be able to ship the project itself we should determine few globla style rules:
- [x] Rename the placeholder of rooms creation (currently _Francis Cabrel OnlyFans)_
- [x] Remove hint _This is an advice_
- [x] Delete `SettingsScreen.tsx`
- [x] Delete references to _Popol_
- [x] forced disconnection screen refactor
- [x] Design a basic item component for MPE lists (Library **and** Search MPE)
- [ ] design a splash screen for the authentication
- [ ] Complete all tasks in comment below 👇
- [x] remove default login value credentials inside login screen
- [ ] ?? Logo ??

**Comment by Devessier** [comment]
## Refactoring plans

### Loaders

If there is no well-designed loader, show nothing during loading, that is, remove ugly `<Text>LOADING</Text>`. If tests need to target an element to ensure there is a loading state, create an empty element that would not be shown to users but can be targetted by tests.

### Error states

Center the text and add padding.

**Comment by prastoin** [comment]
To be done from here:
- [ ] MyProfile && UserProfile design
- [ ] Mpe Item refactor for every mpe search result ( my lib other user etc etc )
- [ ] Home design
- [ ] Bottom sheet modal buttons refactor
