### ISSUE TITLE
42 correction recap and FAQs

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#572]
In this issue we will communicate around the upcoming project 42 correction
Main problematic that could be optional, is to be running the app on a mac at school ( note that they will have a linux OS )
Also the correction scale is not really interesting by itself. We could purpose to the corrector a guided correction raising the in our opinions the most technical interesting and cool points of the application. This would need some preparation to be fully comprehensible and interesting for the corrector.
We will also have to push the repo on the 42 vogsphere and lock the project.

**Comment by prastoin** [comment]
It could be interesting to provide schemas to the corrector about specific "complex" aspect of your project:

Valeures directives:
- State machine
- Strong typing
- Commintlint => git flow pull request reviews etc

Such as:
- Temporal Usage normally versus in our stack
- Mpe xstate actors manipulation + examples with for example a chat
- Google oauth with redirect_uri on app itself
- AppMachine authentication + socket connection on authentication
- e2e test coverage + integration tests coverage for each package ( client, server, temporal )
- Our data model Lucid orm migrations + zod usage data validation etc ( overall adonis benefits )
- Cross platform

**Comment by prastoin** [comment]
tech per package schema

**Comment by Devessier** [comment]
The project has been successfully validated at school.
