### ISSUE TITLE
Refactor Room Creation Funnel, creation, initial Tracks fetched...

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#58]
When a user creates a room a req is sent to temporal to ask for a workflowCreation.
From that request we can synchronously ( e.g in the req's response ) retrieve a:
 - RunID
 - WorkflowID
 - CreatorUserID
 - Users
 
At least everything if it's not the optional initial Tracks a user can ask for.
In the other hand during the workflow initialization which is asynchronous we will find the logic that fetch the initial tracks informations.

When temporal will finish to fetch those tracks ( even if there's not initial tracks ) temporal will make a Use Local Activity to Notify Adonis about something like "Room is ready"
Temporal won't be able to receive any workflow signal until the "Room is ready" Use Local Activity to Notify has been emitted

Described expected behaviour:

1. User emits a CREATE_ROOM from the client
2. Adonis makes a create workflow req to temporal
3. Temporal sends back the synchronously findable informations from what Adonis creates a mtvRoom in pg
with hardcoded tracks = [ ]
4. Client receives back the synchronously findable informations, user can now see the mtvRoom view ( no loader ), but until he receives the "ROOM_IS_READY" ws event the user won't be able to submit any event. ( appMusicPlayerMachine will handle that, temporal will be bullet proof too )
5. Temporal has finished to fetch the initial track, he then sends the Use Local Activity to Notify "Room is ready"
6. Adonis receives the "Room is ready" payload and update if necessary the specified room in postgres, adonis emits a ws event ROOM_READY with optional payload containing the fetched initial tracks
7. User can see fetched initial tracks information in the view / in the player, the state machine is ready user can make ws event.

Why all that ?
To improve room creation fluidity but also global xstate architecture, by moving the initial tracks fetching inside the internalStateMachine in temporal

Why always waiting for the ROOM_READY ws event ?
To avoid a raise condition where the user can suggest a track before the initial track has been fetched and injected in the tracks q.

Not specially ordered Todo List:

**Client**
- [x] Listen to ROOM_READY ws event in the root state machine invoke
- [x] Create a new state in the connectingToRoom state, 'roomBuilding' that will need the ROOM_READY ws to transition to connectedToRoom injecting optional fetched initial tracks
- [ ] Create/update tests **To develop**

**Adonis**
- [x] In TemporalToServer, dev logic around ROOM_READY
- [x] Create/update tests **To develop**

**Temporal**
- [x] Move the inital tracks fetching logic into the internal state machine and make async ( with future ? ) like for the timer management
- [x] Look with a new eye for any updates in the Room is ready activity
- [x] Create/update tests **To develop**

ps: What I call a Use Local Activity to Notify is a http request made by Temporal to Adonis as a consequence to an Adonis http request that generates a workflow signal [see](https://community.temporal.io/t/signalling-system-human-driven-workflows/160/3)
Every new keyword, ws events variables names function names you can find are not definitive at all.

**Comment by Devessier** [comment]
It looks great to me! You will be able to dive in mtv workflow state machine. 👌 

We should determine what information about the tracks of a room will have to be stored in the database. Do we store only IDs? Do we store in addition to IDs the title of the video, the name of its author?
The most important question to answer is if we want to rely on the workflow to get these information on demand, or if we want to cache them in the database. This is an important question as querying the state of the workflow blocks the state machine through a lock.

**Comment by prastoin** [comment]
I agree ! on letting the caching for a later potential improvement ? ( that even won't be necessary )
