### ISSUE TITLE
Improve button to join a MPE room

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#589]
We should improve the design of the button. We need to find the design we want to implement.

<img width="973" alt="CleanShot 2022-04-25 at 18 20 02@2x" src="https://user-images.githubusercontent.com/29370468/165135229-35aa4836-96ab-4656-8bf4-dfc178c1f7ac.png">

**Comment by prastoin** [comment]
https://icons.expo.fyi/Ionicons/enter

**Comment by prastoin** [comment]
We should also set as greylighter the other mpe room screen view buttons when they're disabled, to improve the user experience as he visually will be able to only press the join button
