### ISSUE TITLE
Clients need to play the video the server wants

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#63]
When the current track changes, the Mtv Room Workflow should broadcast the information to all the clients in the room.

It should make a request to the server, with the room id in the body as well as the workflow state.

The server should expose an endpoint to handle this request. The controller of this route should confirm that there is such a room in the application, then it should send an event inside the socket.io room of the mtv room with the content of the tracks list and the current track. Be this event be called `FORCE_UPDATE_CURRENT_TRACK`.

The client should listen to this event from the `appMusicPlayerStateMachine`. When we receive this event, we should switch to the new current track and play it directly.

**Comment by Devessier** [comment]
I think we want something else here.
We do not want to acknowledge the _go to next track_ operation. We want to know which track to play. Currently, when Temporal accepts to go to the next track, all it does is playing this next track, from the beginning. As a consequence, clients receive a `ACTION_PLAY_CALLBACK` event but it has no effect.

One solution to do not introduce another event and to keep things simple would be to send the state of the mtv room workflow, especially the current room, with `ACTION_PAUSE_CALLBACK` and `ACTION_PLAY_CALLBACK` events. It would enable clients synchronization when the current track is paused or resumed as well as when another track has been selected to be played.

**Comment by Devessier** [comment]
Currently we do not need to have the state of the mtv room workflow in the `ACTION_PAUSE_CALLBACK`. We can add it later if we need to.

**Comment by prastoin** [comment]
I agree ! with that
lets merge the state on the already existing ACTION_PLAY_CALLBACK event as the go to next track temporal use local activity to notify
