### ISSUE TITLE
Tracks suggestion

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#87]
Now we have a tracks list that works. Tracks can be played in sequence, each device connected to a room receives the updates in real time, tracks can be paused and resumes as many time the user wants and we have a so much better implementation of tracks timers in the Temporal Workflow.
The next step is to implement tracks suggestion. We no longer want to have a fixed tracks list, we want to populate it through the user interface.

The first step could be to have a _suggested tracks list_ that would be shown under the tracks list on the player. The user would suggest songs through a well defined flow:

1. The user clicks on _Suggest a Track_ button
2. A tracks search screen is shown to the user. _We need to determine how we implement it technically._ Do we hide the full screen and redirect the user to a screen with a search bar? Do we show a modal? Spotify uses a modal to show a tracks selector when the user wants to add tracks to a playlist (see below).
3. The user can search for a song. If the user clicks on the _Add track_ button, the song must be added to the suggestion list
4. The user can also add songs from the main Search Track screen, linked into the bottom bar. See image below.

## The Workflow

In the Temporal Workflow, we should have a slice that owns all the suggested tracks. This slice would be of type `[]shared.TrackMetadata`.
When we receive, through a signal, that a user suggested a track, we should compare the id the signal contains with all the scheduled tracks and all the suggested tracks. We do not allow duplicates. However, if the suggested track has already been played, we allow it to be suggested again.
Once we verified that the suggested track is not a duplicate, we should fetch its information from YouTube API and assign it to the suggested tracks slice.

When a suggested track is accepted, we should call an activity that broadcast the information to all the clients. To ease the flow we can send all the workflow state, as we did previously.

## UX

_What do we show to the user while we verify that the track she suggested can be added? Does she stay on the search track screen, with a loading spinner?_

### Front-end

- [x] Create search tracks modal
- [x] Show search track modal when _Suggest a Track_ button is pressed
- [x] Allow to quit the modal
- [x] When a song is pressed, close the modal and go back to the full screen player
- [x] Send the selected track to suggest with an event to the back-end
- [x] Wait for the back-end acknowledgement through a WS event
- [x] Show a toast when we received the response
- [x] Wait for an event that is sent by the back-end when a track is suggest ; merge the workflow state with the machine context

### Back-end

- [x] Wait for events sent by the client with a track to suggest
- [x] Broadcast the request to Temporal
- [x] Wait for Temporal acknowledgement of the suggestion
- [x] Broadcast the response of Temporal to the client

### Temporal

- [x] Wait for requests sent by the back-end with the track to suggest
- [x] Send it with a signal to the workflow
- [x] Create a list of suggest tracks
- [x] Append the suggested track to the list if there are no duplicates
- [x] If the track could be suggested, broadcast the information to the back-end by sending the workflow state

### Spotify tracks list adding modal

![image](https://user-images.githubusercontent.com/29370468/128524810-e3a00045-913e-496b-9c7b-d3f9ea17c794.png)

### Options on searched tracks

![image](https://user-images.githubusercontent.com/29370468/128677173-9ee09898-36ba-43b8-8366-c66432d8cbb0.png)

**Comment by prastoin** [comment]
>We need to determine how we implement it technically. Do we hide the full screen and redirect the user to a screen with a search bar? Do we show a modal?

I think we should display a basic 100% 100% modal above the musicPlayer

> What do we show to the user while we verify that the track she suggested can be added? Does she stay on the search track screen, with a loading spinner?

I guess we should display a spinner as it should not take too long to manage the request

**Comment by Devessier** [comment]
On success we could display a toast, such as with this library: https://www.npmjs.com/package/react-native-toast-message.

Let's keep in mind the great UX interaction that is to scroll to the added song, but I do not know if it's easily feasible.

**Comment by prastoin** [comment]
:bread:
