### ISSUE TITLE
As a user choose a device to play music on

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#88]
### Choose a device to play music on
As we can now relate devices to a user. We should now be able to implement the choose a device to play the music on feature.

The user should be able via the music player full screen to see his alive-sessions related ( connected ) devices.
And then be able to switch the playing music device.
This features is all about: 
Allow the user to choose a device to play the music on.
To be able to list connected user's devices

Technically we need to do:

Client:
---
 - [x] Put the musicPlayer volume to 0 if the device is not the emitting one
 - [x] At the contrary set the volume to 100 if the device is the emitting one.
 
Both of the points above are computes by the client through a new listened socket event `"ACTION_CHANGE_EMITTING_DEVICE_CALLBACK"`.
As always the payload will be a shallow copy of the `MtvWorkflowState` at time T.
It'll be then merged in the `appMusicPlayerStateMachine` via the `assignMergeNewState`.
It involves to update the `exposedMtvWorkflowState` to persist user scoped information, such as the emitting device uid.
 - [x] List the users's currently alive sessions ( connected ) devices, and allow him to pick one as emitting
 It involves to update the `appMusicPlayerContext` to persist user connected devices, such as context.devices ( string[ ] )
- [x] Create a context provider around the user informations
- [x] Create a state machine that will be useful later for the auth, but where for the moment we will listen to `CONNECTED_DEVICES_UPDATE` socket event

This feature will be the first step in the Authentication/User scoped development.
We would like to create a context provider that will manage the user related information, such as here specifically the user connected devices listener etc
 
Server nor Types:
---
- [x] Create and handle `"CHANGE_EMITTING_DEVICE"` socket event, containing a device uid in the payload. 
Check if the given `deviceUid` is well emitting user related
It should then persist the operation to the user corresponding mtv room workflow
- [x] Create and handle the new temporal Http callback request corresponding to the "CHANGE_EMITTING_DEVICE" acknowledgment and send back a socket 
"ACTION_CHANGE_EMITTING_DEVICE_CALLBACK" event to the user socket instance.
- [x] Add the user emitting device uid to the CREATE_WORKFLOW and JOIN_WORKFLOW payloads and persist them in the temporal `internalState`. Default emitting device uid will be the socket event emitter.
- [x] test above features

We have a need, be able to retrieve user's connected devices. But does it really deserved to be in the `MtvWorkflowState` ? We will later need to implement new user scoped controllers to display user's profile. I think the user's connected devices is more closer to a `userController` business than a `MtvRoomController`.
I think that we should leave the connected devices to a specific socket event such as "CONNECTED_DEVICES_UPDATE" that would be sent to all the user's connected device containing just an array of device uid
This event would be listened by the `appMusicPlayer` machine and would be merged in a `appMusicPlayerContext` specific props ( devices )
In this way we should
- [x] Send a `"CONNECTED_DEVICES_UPDATE"` to all user's connected devices on a related Socket connection and disconnect event
- [x] Create a `userController` that will manage the CONNECTED_DEVICES_UPDATE construction
- [x] When a device disconnect we need to detect is he was emitting the music, if yes change by an an other ( latest ) connected device, send to temporal a `changeUserEmittingDevice` signal with the new `deviceID`.
- [x] To be able to detect if the evicted device was the playing one, we should store in the Device model a new boolean such as `CurrentlyEmitting` default to false that will turn true on a Temporal `ChangeUserEmittingDevice` acknowledgment request
- [x] test above two features
- [x] For web app only create a custom deviceName based on the user agent

It's more about building the first step of the authentication stairs
 

Temporal:
---
- [x] Add a `emittingDeviceUuid` props for each user in the `internalState`
- [x] Create a route and a workflow signal to allow the user to change his `emittingDeviceUid`
- [x] Create an activity to alert adonis about the change

**Comment by prastoin** [comment]
I on purpose do not store all the user's connected devices uuid in the temporal internalState as it's adonis responsability.
I imagine more temporal as the MtvRoom manager aka music scoped and Adonis as the User manager aka user scoped

**Comment by Devessier** [comment]
I agree with you.
I think we should also store the name of each device. We could do as Spotify and show the list with readable names.
<img width="1792" alt="CleanShot 2021-08-09 at 10 29 47@2x" src="https://user-images.githubusercontent.com/29370468/128679447-eddacc94-39ed-468c-86f2-abd3faf25545.png">


With Expo it seems to be feasible : https://docs.expo.dev/versions/latest/sdk/device/#devicedevicename. Perhaps is it a bit more difficult for the Web?

**Comment by prastoin** [comment]
Yes you're right !
Great for the expo solution
I don't think we'll have specific issue with the web compatibility as we can see here
![image](https://user-images.githubusercontent.com/45004772/128679841-f2287d17-f7ff-4853-9e42-84a4518e2f95.png)

**Comment by prastoin** [comment]
UDPATE:
This feature will be the first step in the Authentification/User scoped dev.
We would like to create a contextProvider that will manage the user related informations, such as here specifically the user connected devices listener etc

Then in the client we need to:
- [ ] Create a context provider around the user informations
- [ ] Create a state machine that will be usefull later for the auth, but where ftm we wil listen to CONNECTED_DEVICES_UPDATE socket event

In adonis :
- [ ] Create a userController that will manage the CONNECTED_DEVICES_UPDATE emittion

It's more about building the first step of the authentication stairs

**Comment by prastoin** [comment]
In temporal I've changed the `internalState.Users` definition from a string slice to a map of new user definition pointers with userID as key ( key is then a string ).
In this way the `internalState.export()` does now not share other users information to every client, such as for the moment the user emitting device uid.
internalState.export does now take an 'optionnal' argument that is userID, if the userID is set in the `exposedInternalState` will be found a userRelatedInformations that is the `internalState.Users[givenUserID]` value else nothing.
To retrieve in the client the number of users in the room we're now using `internalState.UsersLength` which is constantly set what ever given args to `internalState.export`

here you'll find the related code/commit
[first related commit](https://github.com/AdonisEnProvence/MusicRoom/commit/ef8d19e7d6b9696cc5890b9df9ca14212a17474e)
[second related commit](https://github.com/AdonisEnProvence/MusicRoom/commit/d11fddad89cb30fceb80eddf06a4c521784077fc)

**Comment by prastoin** [comment]
REMINDER TO TEST: on join between two // same web user sessions the non emitting one doesn't start after a play ??? because unfocus ??
I'll check that deeper after curr q
